-- 코드를 작성해주세요
WITH SECOND_GEN AS(
    SELECT ID 
    FROM ECOLI_DATA
    WHERE PARENT_ID IN (SELECT ID FROM ECOLI_DATA WHERE PARENT_ID IS NULL)
)

SELECT ID 
FROM ECOLI_DATA
WHERE PARENT_ID IN (SELECT ID FROM SECOND_GEN)
ORDER BY ID;