-- 코드를 입력하세요
SELECT USER_ID, PRODUCT_ID
FROM (SELECT USER_ID, PRODUCT_ID, COUNT(*) AS CNT FROM ONLINE_SALE GROUP BY USER_ID, PRODUCT_ID HAVING CNT>1) AS T
WHERE USER_ID=T.USER_ID AND PRODUCT_ID=T.PRODUCT_ID
ORDER BY USER_ID, PRODUCT_ID DESC
;