-- 코드를 입력하세요
WITH T AS (
    SELECT *, ROW_NUMBER() OVER(PARTITION BY FOOD_TYPE ORDER BY FOOD_TYPE DESC, FAVORITES DESC) AS RN
    FROM REST_INFO
)

SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM T
WHERE RN = 1
ORDER BY FOOD_TYPE DESC;