-- 코드를 입력하세요
WITH T AS (
    SELECT *, ROW_NUMBER() OVER (PARTITION BY CAR_ID ORDER BY END_DATE DESC) AS RN
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE<'2022-10-17'
)

SELECT A.CAR_ID, IF(T.END_DATE>'2022-10-15','대여중','대여 가능') AS AVAILABILITY
FROM (SELECT DISTINCT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY) A LEFT JOIN T ON A.CAR_ID=T.CAR_ID
WHERE RN = 1 OR RN IS NULL
ORDER BY A.CAR_ID DESC
;