-- 코드를 작성해주세요
SELECT CONCAT(QUARTER, "Q") AS QUARTER, ECOLI_COUNT
FROM (
SELECT ((MONTH(DIFFERENTIATION_DATE)-1) DIV 3)+1 AS QUARTER, COUNT(*) AS ECOLI_COUNT
FROM ECOLI_DATA
GROUP BY ((MONTH(DIFFERENTIATION_DATE)-1) DIV 3)+1) AS T