-- 코드를 작성해주세요
WITH T AS (
    SELECT B.EMP_NO, B.EMP_NAME, B.SAL,
    CASE 
    WHEN AVG(C.SCORE) < 80 THEN 'C'
    WHEN AVG(C.SCORE) < 90 THEN 'B'
    WHEN AVG(C.SCORE) < 96 THEN 'A'
    ELSE 'S' END AS GRADE
    FROM (HR_DEPARTMENT A JOIN HR_EMPLOYEES B ON A.DEPT_ID=B.DEPT_ID) 
    JOIN HR_GRADE C ON B.EMP_NO=C.EMP_NO
    GROUP BY B.EMP_NO
)

SELECT EMP_NO, EMP_NAME, GRADE,
SAL*(CASE
WHEN GRADE = 'C' THEN 0
WHEN GRADE = 'B' THEN 0.1
WHEN GRADE = 'A' THEN 0.15
ELSE 0.2 END) AS BONUS
FROM T
ORDER BY EMP_NO;