SELECT A.MEMBER_NAME, B.REVIEW_TEXT, DATE_FORMAT(B.REVIEW_DATE,'%Y-%m-%d') AS REVIEW_DATE
FROM MEMBER_PROFILE A JOIN REST_REVIEW B ON A.MEMBER_ID=B.MEMBER_ID
WHERE B.MEMBER_ID IN (
    SELECT MEMBER_ID
    FROM REST_REVIEW
    WHERE MEMBER_ID IN (
        SELECT MEMBER_ID 
        FROM (
            SELECT MEMBER_ID, RANK() OVER (ORDER BY COUNT(*) DESC) AS RN
            FROM REST_REVIEW
            GROUP BY MEMBER_ID
        ) AS T
        WHERE RN = 1
    )
)
ORDER BY REVIEW_DATE, B.REVIEW_TEXT;