-- 코드를 입력하세요
WITH T AS (
    SELECT *, ROW_NUMBER() OVER (PARTITION BY CATEGORY ORDER BY CATEGORY, PRICE DESC) AS RN
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN ('과자','국','김치','식용유')
)

SELECT CATEGORY, PRICE AS MAX_PRICE, PRODUCT_NAME
FROM T
WHERE RN = 1
ORDER BY PRICE DESC
;